# Site settings
title: DeLancey's Work
email: 
description: >
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.delancey.work" # the base hostname & protocol for your site
twitter_username: jaysondelancey
github_username:  j12y

